//
//  Question.swift
//  QuizApp
//
//  Created by jaemin park on 2022/01/23.
//

import Foundation

struct Question: Hashable {
    let questionText: String
    let possibleAnswers: [String]
    let correctAnswerIndex: Int
    
    static let allQuestions: [Question] = [
     Question(questionText: "다음 한자를 히라가나로 올바르게 읽은것을 보기에서 찾으세요.雨",
             possibleAnswers: [
             "ゆき",
             "はれ",
             "くもり",
             "あめ",
             ],
             correctAnswerIndex: 3),
    Question(questionText: "다음 한자를 히라가나로 올바르게 읽은것을 보기에서 찾으세요.書いて",
             possibleAnswers: [
             "かいて",
             "きいて",
             "はいて",
             "ひいて",
             ],
             correctAnswerIndex: 0),
    Question(questionText: "다음 한자를 히라가나로 올바르게 읽은것을 보기에서 찾으세요.中",
             possibleAnswers: [
             "そば",
             "そと",
             "なか",
             "よこ",
             ],
             correctAnswerIndex: 2),
    Question(questionText: "다음 한자를 히라가나로 올바르게 읽은것을 보기에서 찾으세요.小さい",
             possibleAnswers: [
             "ちいさい",
             "ちさい",
             "しいさい",
             "しさい",
             ],
             correctAnswerIndex: 0),
    Question(questionText: "다음 한자를 히라가나로 올바르게 읽은것을 보기에서 찾으세요.火よう日",
             possibleAnswers: [
             "どようび",
             "すいようび",
             "かようび",
             "にちようび",
             ],
             correctAnswerIndex: 2),
    Question(questionText: "다음 한자를 히라가나로 올바르게 읽은것을 보기에서 찾으세요.空",
             possibleAnswers: [
             "いえ",
             "うみ",
             "にわ",
             "そら",
             ],
             correctAnswerIndex: 3),
    Question(questionText: "다음 한자를 히라가나로 올바르게 읽은것을 보기에서 찾으세요.百人",
             possibleAnswers: [
             "ひゃくにん",
             "びゃくにん",
             "ひゃくじん",
             "びゃくじん",
             ],
             correctAnswerIndex: 0),
    Question(questionText: "다음 한자를 히라가나로 올바르게 읽은것을 보기에서 찾으세요.魚",
             possibleAnswers: [
             "ねこ",
             "とり",
             "いぬ",
             "さかな",
             ],
             correctAnswerIndex: 3),
    Question(questionText: "다음 한자를 히라가나로 올바르게 읽은것을 보기에서 찾으세요.半分",
             possibleAnswers: [
             "はんふん",
             "はんぶん",
             "ほんぶん",
             "ほんふん",
             ],
             correctAnswerIndex: 1),
    Question(questionText: "다음 한자를 히라가나로 올바르게 읽은것을 보기에서 찾으세요.?間",
             possibleAnswers: [
             "あいた",
             "となり",
             "あいだ",
             "どなり",
             ],
             correctAnswerIndex: 2),
    Question(questionText: "다음 한자를 히라가나로 올바르게 읽은것을 보기에서 찾으세요.三つ",
             possibleAnswers: [
             "いつつ",
             "みっつ",
             "さんつ",
             "ごつ",
             ],
             correctAnswerIndex: 1),
    Question(questionText: "다음 한자를 히라가나로 올바르게 읽은것을 보기에서 찾으세요.元気",
             possibleAnswers: [
             "けんき",
             "げんき",
             "でんき",
             "てんき",
             ],
             correctAnswerIndex: 1),
    Question(questionText: "다음 히리가나를 카타카나로 올바르게 읽은것을 보기중에 고르시오.わいしゃつ",
             possibleAnswers: [
             "ウイシャソ",
             "ウイシャツ",
             "ワイシャソ",
             "ワイシャツ",
             ],
             correctAnswerIndex: 3),
    Question(questionText: "다음 히라가나를 한자 올바르게 쓴것을 보기중에 고르세요.かわ",
             possibleAnswers: [
             "花",
             "山",
             "川",
             "木",
             ],
             correctAnswerIndex: 2),
    Question(questionText: "다음 히라가나를 한자로 올바르게 쓴것을 보기중에 고르세요.がっこう",
             possibleAnswers: [
             "宇校",
             "学校",
             "宇枚",
             "学枚",
             ],
             correctAnswerIndex: 1),
    Question(questionText: "다음 히라가나를 한자로 올바르게 쓴것을 보기중에 고르세요.みて",
             possibleAnswers: [
             "見て",
             "買て",
             "貝て",
             "目て",
             ],
             correctAnswerIndex: 0),
    Question(questionText: "다음 히라가나를 한자로 올바르게 쓴것을 보기중에 고르세요.たかい",
             possibleAnswers: [
             "高い",
             "安い",
             "古い",
             "新い",
             ],
             correctAnswerIndex: 0),
    Question(questionText: "다음 히라가나를 한자로 올바르게 쓴것을 보기중에 고르세요.かいしゃ",
             possibleAnswers: [
             "公仕",
             "公社",
             "会仕",
             "会社",
             ],
             correctAnswerIndex: 3),
    Question(questionText: "다음 한자를 히라가나로 올바르게 읽은것을 보기에서 찾으세요.いわないで",
             possibleAnswers: [
             "行わないで",
             "立わないで",
             "言わないで",
             "食わないで",
             ],
             correctAnswerIndex: 2),
    Question(questionText: "다음 한자를 히라가나로 올바르게 읽은것을 보기에서 찾으세요.らいげつ",
             possibleAnswers: [
             "今月",
             "来月",
             "来週",
             "今週",
             ],
             correctAnswerIndex: 1),
    Question(questionText: "다음 일본어 문장을 읽고 괄호 안에 들어갈 알맞은 단어를 보기에서 고르세요.わたしの へやは この アパートの 2(❓)です.",
             possibleAnswers: [
             "ほん",
             "さつ",
             "だい",
             "かい",
             ],
             correctAnswerIndex: 3),
    Question(questionText: "다음 일본어 문장을 읽고 괄호 안에 들어갈 알맞은 단어를 보기에서 고르세요.その ナイフで りんごを(❓)ください。",
             possibleAnswers: [
             "おきて",
             "つけて",
             "しめて",
             "きって",
             ],
             correctAnswerIndex: 3),
    Question(questionText: "다음 일본어 문장을 읽고 괄호 안에 들어갈 알맞은 단어를 보기에서 고르세요.(❓)を わすれましたから、じかんが わかりません。",
             possibleAnswers: [
             "じしょ",
             "ちず",
             "とけい",
             "さいふ",
             ],
             correctAnswerIndex: 2),
    Question(questionText: "다음 일본어 문장을 읽고 괄호 안에 들어갈 알맞은 단어를 보기에서 고르세요.わたしの うちは えきに ちかいですから、(❓)です。",
             possibleAnswers: [
             "べんり",
             "じょうぶ",
             "いっぱい",
             "へた",
             ],
             correctAnswerIndex: 0),
    Question(questionText: "다음 일본어 문장을 읽고 괄호 안에 들어갈 알맞은 단어를 보기에서 고르세요.?なつやすみは まいにち(❓)で およぎました。",
             possibleAnswers: [
             "レストラン",
             "プール",
             "エレベーター",
             "ビル",
             ],
             correctAnswerIndex: 1),
    Question(questionText: "다음 일본어 문장을 읽고 괄호 안에 들어갈 알맞은 단어를 보기에서 고르세요.しらない ことばが ありましたから、せんせいに(❓)しました。",
             possibleAnswers: [
             "しつもん",
             "べんきょう",
             "れんしゅう",
             "じゅぎょう",
             ],
             correctAnswerIndex: 0),
    Question(questionText: "다음 일본어 문장을 읽고 괄호 안에 들어갈 알맞은 단어를 보기에서 고르세요.この へやは あついですから、(❓)を あけましょう。",
             possibleAnswers: [
             "おふろ",
             "まど",
             "エアコン",
             "テーブル",
             ],
             correctAnswerIndex: 1),
    Question(questionText: "다음 일본어 문장을 읽고 괄호 안에 들어갈 알맞은 단어를 보기에서 고르세요.きのうは がっこうで たくさん かんじを(❓)",
             possibleAnswers: [
             "うりました",
             "もちました",
             "おぼえました",
             "こまりました",
             ],
             correctAnswerIndex: 2),
    Question(questionText: "다음 일본어 문장을 읽고 괄호 안에 들어갈 알맞은 단어를 보기에서 고르세요.この コーヒーは、さとうを たくさん いれましたから、 (❓)です。",
             possibleAnswers: [
             "わかい",
             "くろい",
             "まるい",
             "あまい",
             ],
             correctAnswerIndex: 3),
    Question(questionText: "다음 일본어 문장을 읽고 괄호 안에 들어갈 알맞은 단어를 보기에서 고르세요.つよい かぜが (❓) います。",
             possibleAnswers: [
             "ふいて",
             "いそいで",
             "とんで",
             "はしって",
             ],
             correctAnswerIndex: 0),
        Question(questionText: "다음 단어를 올바르게 읽는 방법은?楽しかった",
             possibleAnswers: [
             "いそがしかった",
             "すずしかった",
             "たのしかった",
             "かなしかった",
             ],
             correctAnswerIndex: 2),
        Question(questionText: "다음 단어를 올바르게 읽는 방법은?味",
             possibleAnswers: [
             "かたち",
             "いろ",
             "におい",
             "あじ",
             ],
             correctAnswerIndex: 3),
        Question(questionText: "다음 단어를 올바르게 읽는 방법은?不便",
             possibleAnswers: [
             "ふべん",
             "ぶべん",
             "ふへん",
             "ぶへん",
             ],
             correctAnswerIndex: 0),
        Question(questionText: "다음 단어를 올바르게 읽는 방법은?切って",
             possibleAnswers: [
             "とって",
             "きって",
             "あらって",
             "もって",
             ],
             correctAnswerIndex: 1),
        Question(questionText: "다음 단어를 올바르게 읽는 방법은?以外",
             possibleAnswers: [
             "にそと",
             "にがい",
             "いそと",
             "いがい",
             ],
             correctAnswerIndex: 3),
        Question(questionText: "다음 단어를 올바르게 읽는 방법은?雲",
             possibleAnswers: [
             "ほし",
             "ゆき",
             "くも",
             "そら",
             ],
             correctAnswerIndex: 2),
        Question(questionText: "다음 단어를 올바르게 읽는 방법은?急行",
             possibleAnswers: [
             "きゅこ",
             "きゅこう",
             "きゅうこ",
             "きゅうこう",
             ],
             correctAnswerIndex: 3),
        Question(questionText: "다음 단어를 올바르게 읽는 방법은?写さないで",
             possibleAnswers: [
             "おさないで",
             "うつさないで",
             "けさないで",
             "おとさないで",
             ],
             correctAnswerIndex: 1),
        Question(questionText: "다음 단어를 올바르게 읽는 방법은?反対",
             possibleAnswers: [
             "はんたい",
             "ほんたい",
             "はんだい",
             "ほんだい",
             ],
             correctAnswerIndex: 0),
        Question(questionText: "다음 단어를 올바르게 쓰는 방법은?くろい",
             possibleAnswers: [
             "白い",
             "黒い",
             "赤い",
             "青い",
             ],
             correctAnswerIndex: 1),
        Question(questionText: "다음 단어를 올바르게 쓰는 방법은?けいかく",
             possibleAnswers: [
             "計書",
             "訂画",
             "計画",
             "訂書",
             ],
             correctAnswerIndex: 2),
        Question(questionText: "다음 단어를 올바르게 쓰는 방법은?いしゃ",
             possibleAnswers: [
             "匠員",
             "医員",
             "匠者",
             "医者",
             ],
             correctAnswerIndex: 3),
        Question(questionText: "다음 단어를 올바르게 쓰는 방법은?よる",
             possibleAnswers: [
             "夜",
             "昼",
             "夕",
             "朝",
             ],
             correctAnswerIndex: 0),
        Question(questionText: "다음 단어를 올바르게 쓰는 방법은?かして",
             possibleAnswers: [
             "貨して",
             "資して",
             "貸して",
             "質して",
             ],
             correctAnswerIndex: 2),
        Question(questionText: "다음 단어를 올바르게 쓰는 방법은?しあい",
             possibleAnswers: [
             "誡会",
             "誡合",
             "試会",
             "試合",
             ],
             correctAnswerIndex: 3),
        Question(questionText: "다음 단어를 올바르게 쓰는 방법은?しあい",
             possibleAnswers: [
             "誡会",
             "誡合",
             "試会",
             "試合",
             ],
             correctAnswerIndex: 3),
        Question(questionText: "다음 일본어 문장의 괄호안에 알맞은 단어는?さとうさんが けがを したと 聞いて、みんな(❓)しました。",
             possibleAnswers: [
             "しんぱい",
             "けいけん",
             "しつれい",
             "おじぎ",
             ],
             correctAnswerIndex: 0),
        Question(questionText: "다음 일본어 문장의 괄호안에 알맞은 단어는?わたしには、しょうらい かしゅに なると いう(❓)が あります。",
             possibleAnswers: [
             "けしき",
             "ゆめ",
             "おもいで",
             "せわ",
             ],
             correctAnswerIndex: 1),
        Question(questionText: "다음 일본어 문장의 괄호안에 알맞은 단어는?わたしには、しょうらい かしゅに なると いう(❓)が あります。",
             possibleAnswers: [
             "けしき",
             "ゆめ",
             "おもいで",
             "せわ",
             ],
             correctAnswerIndex: 1),
        Question(questionText: "다음 일본어 문장의 괄호안에 알맞은 단어는?リーさんも こんどの パーティーに(❓)来て くださいね。",
             possibleAnswers: [
             "ひじょうに",
             "ぜひ",
             "じゅうぶん",
             "いつも",
             ],
             correctAnswerIndex: 1),
        Question(questionText: "다음 일본어 문장의 괄호안에 알맞은 단어는?これから きかいの つかいかたを(❓)しますから、よく 聞いてください。",
             possibleAnswers: [
             "じゅんび",
             "りよう",
             "せつめい",
             "せいさん",
             ],
             correctAnswerIndex: 2),
        Question(questionText: "다음 일본어 문장의 괄호안에 알맞은 단어는?はが わるいので、(❓)ものは 食べられません。",
             possibleAnswers: [
             "きびしい",
             "かたい",
             "はやい",
             "ふかい",
             ],
             correctAnswerIndex: 1),
        Question(questionText: "다음 일본어 문장의 괄호안에 알맞은 단어는?もりさんを デートに(❓)が、行けないと 言われました。",
             possibleAnswers: [
             "さそいました",
             "つたえました",
             "あんないしました",
             "しょうかいしました",
             ],
             correctAnswerIndex: 0),
        Question(questionText: "다음 일본어 문장의 괄호안에 알맞은 단어는?わたしの むすこは、 1年で 5(❓)くらい せが 高く なりました。",
             possibleAnswers: [
             "グラム",
             "ばん",
             "けん",
             "センチ",
             ],
             correctAnswerIndex: 3),
        Question(questionText: "다음 일본어 문장의 괄호안에 알맞은 단어는?お店で 3だいの パソコンを(❓)、いちばん かるい パソコンをえらびました。。",
             possibleAnswers: [
             "かたづけて",
             "かぞえて",
             "くらべて",
             "はらって",
             ],
             correctAnswerIndex: 2),
        Question(questionText: "다음 일본어 문장의 괄호안에 알맞은 단어는?たなかさんの いえの 電気が ついて いませんね。たなかさんは(❓)の ようです。",
             possibleAnswers: [
             "うそ",
             "じゆう",
             "ちゅうし ",
             "るす",
             ],
             correctAnswerIndex: 3),
        
    ]
}

      
     
    
          
    
